# Generated by Django 5.0.1 on 2120-12-18 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
    ]
