# Generated by Django 5.0 on 2023-12-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="category",
            field=models.CharField(
                choices=[
                    ("Science", "Science"),
                    ("Technology", "Technology"),
                    ("Engineering", "Engineering"),
                    ("Math", "Math"),
                ],
                default="Technology",
                max_length=30,
            ),
        ),
    ]
