# Generated by Django 5.0 on 2023-12-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_blogpost_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="category",
            field=models.CharField(
                choices=[
                    ("Web Development", "Web Development"),
                    ("AI/ML", "AI/ML"),
                    ("UIUX", "UIUX"),
                    ("Programming", "Programming"),
                    ("Cyber Security", "Cyber Security"),
                ],
                default="Programming",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="description",
            field=models.CharField(max_length=100000),
        ),
    ]
