# Generated by Django 5.0 on 2023-12-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_blogpost_category_alter_blogpost_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="category",
            field=models.CharField(
                choices=[
                    ("Web Development", "Web Development"),
                    ("AI/ML", "AI/ML"),
                    ("UI/UX", "UI/UX"),
                    ("Programming", "Programming"),
                    ("Cyber Security", "Cyber Security"),
                ],
                default="Programming",
                max_length=30,
            ),
        ),
    ]
