# Generated by Django 5.0 on 2023-12-26 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_notification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="time",
            new_name="created_at",
        ),
    ]
