# Generated by Django 5.0 on 2023-12-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.IntegerField(default=234),
        ),
    ]
