# Generated by Django 4.2.8 on 2023-12-28 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_notification_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="comment",
        ),
    ]
